import { createSlice } from "@reduxjs/toolkit";
import type { Post } from "lib/types/postValidator";
import type { PayloadAction } from "@reduxjs/toolkit";
import type { PostsCRUD } from "lib/types/postsCRUD";

// Initial state for the state slice
const initialState: PostsCRUD = {
  postsInfo: {
    currentPage: 1,
    totalPosts: 0,
    pageSize: 10,
    startIndex: 0,
    totalPages: 1,
  },
  postsData: [],
  queryParams: "",
};

// Create a Redux slice using createSlice from @reduxjs/toolkit
const postsCRUDSlice = createSlice({
  name: "postsCRUD",
  initialState,
  reducers: {
    setCurrentPage: (state, action: PayloadAction<number>) => {
      state.postsInfo.currentPage = action.payload;
    },
    setTotalPosts: (state, action: PayloadAction<number>) => {
      state.postsInfo.totalPosts = action.payload;
    },
    setPageSize: (state, action: PayloadAction<number>) => {
      state.postsInfo.pageSize = action.payload;
    },
    setStartIndex: (state, action: PayloadAction<number>) => {
      state.postsInfo.currentPage = action.payload;
    },
    setTotalPages: (state, action: PayloadAction<number>) => {
      state.postsInfo.currentPage = action.payload;
    },
    setPosts: (state, action: PayloadAction<Post[]>) => {
      state.postsData = action.payload;
    },
    setQueryParams: (state, action: PayloadAction<string>) => {
      state.queryParams = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const {
  setTotalPages,
  setTotalPosts,
  setCurrentPage,
  setPageSize,
  setPosts,
  setStartIndex,
  setQueryParams,
} = postsCRUDSlice.actions;

// Export the reducer generated by createSlice
export default postsCRUDSlice.reducer;
