import { createSlice } from "@reduxjs/toolkit";
import type { PayloadAction } from "@reduxjs/toolkit";

// Interfaces for defining types
export interface Post {
  creator: string;
  title: string;
  link: string;
  pubDate: string;
  "dc:creator": string;
  content: string;
  contentSnippet: string;
  guid: string;
  categories: string[];
  isoDate: string;
}

// Initial state for the state slice
const initialState: Post = {
  creator: "",
  title: "",
  link: "",
  "dc:creator": "",
  content: "",
  contentSnippet: "",
  guid: "",
  categories: [],
  isoDate: "",
  pubDate: "",
};

// Create a Redux slice using createSlice from @reduxjs/toolkit
const formSlice = createSlice({
  name: "postValidator",
  initialState,
  reducers: {
    setCreator: (state, action: PayloadAction<string>) => {
      state.creator = action.payload;
    },
    setTitle: (state, action: PayloadAction<string>) => {
      state.title = action.payload;
    },
    setPost: (state, action: PayloadAction<Post>) => {
      state = action.payload;
    },
    setLink: (state, action: PayloadAction<string>) => {
      state.link = action.payload;
    },
    setPubDate: (state, action: PayloadAction<string>) => {
      state.pubDate = action.payload;
    },
    setDcCreator: (state, action: PayloadAction<string>) => {
      state["dc:creator"] = action.payload;
    },
    setContent: (state, action: PayloadAction<string>) => {
      state.content = action.payload;
    },
    setContentSnippet: (state, action: PayloadAction<string>) => {
      state.contentSnippet = action.payload;
    },
    setGuid: (state, action: PayloadAction<string>) => {
      state.guid = action.payload;
    },
    setCategories: (state, action: PayloadAction<string[]>) => {
      state.categories = action.payload;
    },
    setIsoDate: (state, action: PayloadAction<string>) => {
      state.isoDate = action.payload;
    },
    setResetValues: (state) => {
      state.creator = "";
      state.title = "";
      state.link = "";
      state.pubDate = "";
      state["dc:creator"] = "";
      state.content = "";
      state.contentSnippet = "";
      (state.guid = ""), (state.isoDate = "");
      state.categories = [];
      state.isoDate = "";
    },
  },
});

// Export the action creators generated by createSlice
export const {
  setCreator,
  setTitle,
  setLink,
  setPubDate,
  setDcCreator,
  setContent,
  setContentSnippet,
  setPost,
  setGuid,
  setIsoDate,
  setCategories,
  setResetValues,
} = formSlice.actions;

// Export the reducer generated by createSlice
export default formSlice.reducer;
