import { createSlice } from "@reduxjs/toolkit";
import { Post } from "./PostValidator";
import type { PayloadAction } from "@reduxjs/toolkit";

// Interfaces for defining types

interface PostsInfo {
  currentPage: number;
  totalPosts: number;
  postsFound: number;
  pageSize: number;
  startIndex: number;
  totalPages: number;
}

// Interface for defining the state shape
export interface PostsCRUD {
  postsInfo: PostsInfo;
  postsData: Post[];
  queryParams: string;
}

// Initial state for the state slice
const initialState: PostsCRUD = {
  postsInfo: {
    currentPage: 1,
    totalPosts: 0,
    postsFound: 0,
    pageSize: 10,
    startIndex: 0,
    totalPages: 1,
  },
  postsData: [],
  queryParams: "",
};

// Create a Redux slice using createSlice from @reduxjs/toolkit
const postsCRUDSlice = createSlice({
  name: "postsCRUD",
  initialState,
  reducers: {
    setCurrentPage: (state, action: PayloadAction<number>) => {
      state.postsInfo.currentPage = action.payload;
    },
    setTotalPosts: (state, action: PayloadAction<number>) => {
      state.postsInfo.totalPosts = action.payload;
    },
    setPostsFound: (state, action: PayloadAction<number>) => {
      state.postsInfo.postsFound = action.payload;
    },
    setPageSize: (state, action: PayloadAction<number>) => {
      state.postsInfo.pageSize = action.payload;
    },
    setStartIndex: (state, action: PayloadAction<number>) => {
      state.postsInfo.currentPage = action.payload;
    },
    setTotalPages: (state, action: PayloadAction<number>) => {
      state.postsInfo.currentPage = action.payload;
    },
    setPosts: (state, action: PayloadAction<Post[]>) => {
      state.postsData = action.payload;
    },
    setQueryParams: (state, action: PayloadAction<string>) => {
      state.queryParams = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const {
  setTotalPages,
  setTotalPosts,
  setCurrentPage,
  setPageSize,
  setPosts,
  setPostsFound,
  setStartIndex,
  setQueryParams,
} = postsCRUDSlice.actions;

// Export the reducer generated by createSlice
export default postsCRUDSlice.reducer;
